### ISSUE TITLE
Deaths/Hospitalizations

### ISSUE THREAD

**Issue by brentwooldridge** [v1xerunt/STAN#8]
This may be a detail I missed in the paper, but the code seems to turn 'People_Hospitalized' into 'hospitalization'.  On the first day of the downloaded info, May-04-2020, there are 8 recorded deaths and 0 recorded hospitalizations in Alabama.  In the data, there are 298 deaths and 1064 hospitalizations.  What has caused this?

**Comment by v1xerunt** [comment]
Hello, 'In the data, there are 298 deaths and 1064 hospitalizations.', I'm not sure which data are you referring to?

**Comment by brentwooldridge** [comment]
https://github.com/CSSEGISandData/COVID-19/tree/master/csse_covid_19_data/csse_covid_19_daily_reports_us  On May-04-2020 from this link in "data_downloader.py" the "Deaths" entry is 298 and the "People_Hospitalized" entry is 1064.  When I run the code and on the notebook shown as your example "ipynb_checkpoints" the deaths are 8 and the hospitalizations are 0.

**Comment by v1xerunt** [comment]
The Deaths and People_Hospitalized cases in our processed data are actually daily numbers. But in the JHU data, they are total numbers. However, I found that I should use total numbers instead of daily numbers - for death cases only - to calculate the recovery cases. So I have fixed this bug. Thank you for identifying this.

**Comment by brentwooldridge** [comment]
The hospitalizations are 0 for almost the first 100 days.  Why is this?  And the deaths in the JHU dataset are the daily marginal increases, all of which are significantly higher in the dataset than in your notebook.

**Comment by v1xerunt** [comment]
We do not use hospitalization case numbers in the model. But this issue is because there are some data quality issues in the JHU data. So during the preprocess (sorting and calculating daily increase), it affects the final values. Now these issues have been fixed. The death case numbers are now the same as the original data.

**Comment by brentwooldridge** [comment]
In the paper on page 735 under "Node features(dynamic)" it says that the node features are active cases, total cases, **the current number of hospitalizations**, and ICU stays due to Covid-19, which are calculated by aggregating the related procedure codes.(IQVIA)  3 of these 4 can be extracted from the JHU dataset, but are taken from the IQVIA dataset, to which we don't have access.  What problems would using the hospitalization and total cases data from the JHU dataset present if the numbers are valid?  Also, if deaths are fixed, why is the output the same?

**Comment by v1xerunt** [comment]
You can use the JHU data as dynamic features, just like the example notebook. Compared with the real-world claims data, it will affect the prediction accuracy. 

For the death case issue, have you pulled my latest commit? Cause on my end it is correct.
